version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '10:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
